#pragma checksum "C:\Users\User67d3\source\repos\WebAPI\Areas\NormalUser\Views\User\_ViewImports.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a35c7ab4cf0fa3cb92bf92c3e850a39399252e7b"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_NormalUser_Views_User__ViewImports), @"mvc.1.0.view", @"/Areas/NormalUser/Views/User/_ViewImports.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\User67d3\source\repos\WebAPI\Areas\NormalUser\Views\User\_ViewImports.cshtml"
using WebAPI;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\User67d3\source\repos\WebAPI\Areas\NormalUser\Views\User\_ViewImports.cshtml"
using WebAPI.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\User67d3\source\repos\WebAPI\Areas\NormalUser\Views\User\_ViewImports.cshtml"
using WebAPI.Data.DataModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\User67d3\source\repos\WebAPI\Areas\NormalUser\Views\User\_ViewImports.cshtml"
using WebAPI.Constants;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a35c7ab4cf0fa3cb92bf92c3e850a39399252e7b", @"/Areas/NormalUser/Views/User/_ViewImports.cshtml")]
    public class Areas_NormalUser_Views_User__ViewImports : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
