#pragma checksum "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Create.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a7fb282e2183588d8ff23dbcba076f50a72e1a42"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Product_Create), @"mvc.1.0.view", @"/Areas/Admin/Views/Product/Create.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a7fb282e2183588d8ff23dbcba076f50a72e1a42", @"/Areas/Admin/Views/Product/Create.cshtml")]
    public class Areas_Admin_Views_Product_Create : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<WebAPI.Data.DataModels.Product>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"
    <form method=""POST"" 
          asp-controller=""Product"" 
          asp-action=""Create"">
        <div class=""form-group"">
            <label asp-for=""Model"" class=""control-label""></label>
            <input asp-for=""Model"" class=""form-control"" />
            <span asp-validation-for=""Model"" class=""text-danger""></span>
        </div>
        <div class=""form-group"">
            <label asp-for=""ImageURL"" class=""control-label""></label>
            <input asp-for=""ImageURL"" class=""form-control"" />
            <span asp-validation-for=""ImageURL"" class=""text-danger""></span>
        </div>
        <div class=""form-group"">
            <label asp-for=""Price"" class=""control-label""></label>
            <input asp-for=""Price"" class=""form-control"" />
            <span asp-validation-for=""Price"" class=""text-danger""></span>
        </div>
        <div class=""form-group"">
            <label asp-for=""Brand"" class=""control-label""></label>
            <input asp-for=""Brand"" class=""form-control"" />
    ");
            WriteLiteral(@"        <span asp-validation-for=""Brand"" class=""text-danger""></span>
        </div>
        <div class=""form-group"">
            <label asp-for=""Year"" class=""control-label""></label>
            <input asp-for=""Year"" class=""form-control"" />
            <span asp-validation-for=""Year"" class=""text-danger""></span>
        </div>
        <div class=""form-group"">
            <label asp-for=""Description"" class=""control-label""></label>
            <input asp-for=""Description"" class=""form-control"" />
            <span asp-validation-for=""Description"" class=""text-danger""></span>
        </div>

        <button type=""submit"" class=""btn btn-primary"">Create</button>
    </form>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<WebAPI.Data.DataModels.Product> Html { get; private set; }
    }
}
#pragma warning restore 1591
