#pragma checksum "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5894e9752a102267da95ba12e4f3ed2423daa3af"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Product_Delete), @"mvc.1.0.view", @"/Areas/Admin/Views/Product/Delete.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"5894e9752a102267da95ba12e4f3ed2423daa3af", @"/Areas/Admin/Views/Product/Delete.cshtml")]
    public class Areas_Admin_Views_Product_Delete : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<WebAPI.Data.DataModels.Product>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n    <form method=\"POST\"\r\n          asp-controller=\"Poduct\"\r\n          asp-action=\"Delete\"");
            BeginWriteAttribute("asp-route-id", "\r\n          asp-route-id=\"", 130, "\"", 165, 1);
#nullable restore
#line 6 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
WriteAttributeValue("", 156, Model.Id, 156, 9, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">\r\n        <div class=\"form-group\">\r\n            <label asp-for=\"Model\" class=\"control-label\"></label>\r\n            <input asp-for=\"Model\"");
            BeginWriteAttribute("value", " value=\"", 304, "\"", 324, 1);
#nullable restore
#line 9 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
WriteAttributeValue("", 312, Model.Model, 312, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" disabled />
            <span asp-validation-for=""Model"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""ImageURL"" class=""control-label""></label>
            <input asp-for=""ImageURL""");
            BeginWriteAttribute("value", " value=\"", 593, "\"", 616, 1);
#nullable restore
#line 15 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
WriteAttributeValue("", 601, Model.ImageURL, 601, 15, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" disabled />
            <span asp-validation-for=""ImageURL"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Price"" class=""control-label""></label>
            <input asp-for=""Price""");
            BeginWriteAttribute("value", " value=\"", 882, "\"", 902, 1);
#nullable restore
#line 21 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
WriteAttributeValue("", 890, Model.Price, 890, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" disabled />
            <span asp-validation-for=""Price"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Brand"" class=""control-label""></label>
            <input asp-for=""Brand""");
            BeginWriteAttribute("value", " value=\"", 1165, "\"", 1185, 1);
#nullable restore
#line 27 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
WriteAttributeValue("", 1173, Model.Brand, 1173, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" disabled />
            <span asp-validation-for=""Brand"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Year"" class=""control-label""></label>
            <input asp-for=""Year"" data-date=""");
#nullable restore
#line 33 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
                                        Write(Model.Year.ToString("yyyy-MM-dd"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@""" class=""form-control"" disabled />
            <span asp-validation-for=""Year"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Description"" class=""control-label""></label>
            <input asp-for=""Description""");
            BeginWriteAttribute("value", " value=\"", 1766, "\"", 1792, 1);
#nullable restore
#line 39 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Delete.cshtml"
WriteAttributeValue("", 1774, Model.Description, 1774, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"form-control\" disabled />\r\n            <span asp-validation-for=\"Description\" class=\"text-danger\"></span>\r\n        </div>\r\n\r\n        <button type=\"submit\" class=\"btn btn-danger\">Delete</button>\r\n    </form>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<WebAPI.Data.DataModels.Product> Html { get; private set; }
    }
}
#pragma warning restore 1591
