#pragma checksum "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "63adb0b5051a9b766216d1116c1ce7e10a9d0fa3"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_Product_Edit), @"mvc.1.0.view", @"/Areas/Admin/Views/Product/Edit.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"63adb0b5051a9b766216d1116c1ce7e10a9d0fa3", @"/Areas/Admin/Views/Product/Edit.cshtml")]
    public class Areas_Admin_Views_Product_Edit : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<WebAPI.Data.DataModels.Product>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n    <form method=\"POST\"\r\n          asp-controller=\"Phone\"\r\n          asp-action=\"Edit\"");
            BeginWriteAttribute("asp-route-id", "\r\n          asp-route-id=\"", 127, "\"", 162, 1);
#nullable restore
#line 6 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
WriteAttributeValue("", 153, Model.Id, 153, 9, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">\r\n\r\n        <div class=\"form-group\">\r\n            <label asp-for=\"Model\" class=\"control-label\"></label>\r\n            <input asp-for=\"Model\"");
            BeginWriteAttribute("value", " value=\"", 303, "\"", 323, 1);
#nullable restore
#line 10 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
WriteAttributeValue("", 311, Model.Model, 311, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" />
            <span asp-validation-for=""Model"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""ImageURL"" class=""control-label""></label>
            <input asp-for=""ImageURL""");
            BeginWriteAttribute("value", " value=\"", 583, "\"", 606, 1);
#nullable restore
#line 16 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
WriteAttributeValue("", 591, Model.ImageURL, 591, 15, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" />
            <span asp-validation-for=""ImageURL"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Price"" class=""control-label""></label>
            <input asp-for=""Price""");
            BeginWriteAttribute("value", " value=\"", 863, "\"", 883, 1);
#nullable restore
#line 22 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
WriteAttributeValue("", 871, Model.Price, 871, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"form-control\" />\r\n            <span asp-validation-for=\"Price\" class=\"text-danger\"></span>\r\n        </div>\r\n\r\n        <div class=\"form-group\">\r\n            <label asp-for=\"Brand\" class=\"control-label\"></label>\r\n            <input asp-for=\"Brand\"");
            BeginWriteAttribute("value", " value=\"", 1137, "\"", 1157, 1);
#nullable restore
#line 28 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
WriteAttributeValue("", 1145, Model.Brand, 1145, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""form-control"" />
            <span asp-validation-for=""Brand"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Year"" class=""control-label""></label>
            <input asp-for=""Year"" data-date=""");
#nullable restore
#line 34 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
                                        Write(Model.Year.ToString("yyyy-MM-dd"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@""" class=""form-control"" />
            <span asp-validation-for=""Year"" class=""text-danger""></span>
        </div>

        <div class=""form-group"">
            <label asp-for=""Description"" class=""control-label""></label>
            <input asp-for=""Description""");
            BeginWriteAttribute("value", " value=\"", 1720, "\"", 1746, 1);
#nullable restore
#line 40 "C:\Users\User67d3\source\repos\WebAPI\Areas\Admin\Views\Product\Edit.cshtml"
WriteAttributeValue("", 1728, Model.Description, 1728, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"form-control\" />\r\n            <span asp-validation-for=\"Description\" class=\"text-danger\"></span>\r\n        </div>\r\n\r\n        <button type=\"submit\" class=\"btn btn-primary\">Edit</button>\r\n    </form>\r\n\r\n\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<WebAPI.Data.DataModels.Product> Html { get; private set; }
    }
}
#pragma warning restore 1591
