#pragma checksum "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7401cb584303963e4b75569c5dbcf4d250cac0f6"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Product_Details), @"mvc.1.0.view", @"/Views/Product/Details.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\User67d3\source\repos\WebAPI\Views\_ViewImports.cshtml"
using WebAPI;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\User67d3\source\repos\WebAPI\Views\_ViewImports.cshtml"
using WebAPI.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\User67d3\source\repos\WebAPI\Views\_ViewImports.cshtml"
using WebAPI.Data.DataModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\User67d3\source\repos\WebAPI\Views\_ViewImports.cshtml"
using WebAPI.Constants;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"7401cb584303963e4b75569c5dbcf4d250cac0f6", @"/Views/Product/Details.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a35c7ab4cf0fa3cb92bf92c3e850a39399252e7b", @"/Views/_ViewImports.cshtml")]
    public class Views_Product_Details : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Product>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n<div class=\"row\">\r\n    <div col=\"6\">\r\n        <img");
            BeginWriteAttribute("src", " src=\"", 68, "\"", 89, 1);
#nullable restore
#line 5 "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml"
WriteAttributeValue("", 74, Model.ImageURL, 74, 15, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" alt=\"product\" />\r\n    </div>\r\n    <div col=\"6\">\r\n        <div>Model: ");
#nullable restore
#line 8 "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml"
               Write(Model.Model);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n        <div>Year: ");
#nullable restore
#line 9 "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml"
              Write(Model.Year);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n        <div>Price: ");
#nullable restore
#line 10 "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml"
               Write(Model.Price);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n        <div>Brand: ");
#nullable restore
#line 11 "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml"
               Write(Model.Brand);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n        <div>Description: ");
#nullable restore
#line 12 "C:\Users\User67d3\source\repos\WebAPI\Views\Product\Details.cshtml"
                     Write(Model.Description);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n    </div>\r\n</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Product> Html { get; private set; }
    }
}
#pragma warning restore 1591
